### ISSUE TITLE
Use new SCC logo

### ISSUE THREAD

**Issue by enolive** [enolive/datev-scc-theme#1]
affected files:

- PNG file for editor background
- Plugin Icon SVG

@Fischermaen, could you submit a PR? :wink:

**Comment by Fischermaen** [comment]
Everything's fine for now? Would you mind bringing the datev-scc-theme in our gitlab repo inside DATEV?

**Comment by enolive** [comment]
Having trouble with publishing the plugin, see also https://github.com/JetBrains/gradle-intellij-plugin/issues/447

Opened a request to JetBrains, will have to wait a couple of days...

There is also a hassle with mirroring plugins to a company internal repo, which is a real chore with keeping updates in sync. But we can put the binary artifacts in some safe place ;-)

**Comment by enolive** [comment]
sucessfully submitted new version of the plugin to JetBrains. Should be publicly available in the next 2 days
